force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/Regional_ManagerId__c.field-meta.xml
<CustomField>
    <fullName>Regional_ManagerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/controllers/RegionController/RegionController.cls
public with sharing class RegionController {
  @AuraEnabled(cacheable=true)
  public static List<RegionDTO> getRegions() {
    List<RegionDTO> lstRegionDTO = new List<RegionDTO>();
    for (Region__c r : [
      SELECT Id, Name
      FROM Region__c
      WITH SECURITY_ENFORCED
      ORDER BY Name
    ]) {
      RegionDTO regionDTO = new RegionDTO();
      regionDTO.id = r.Id;
      regionDTO.name = r.Name;
      lstRegionDTO.add(regionDTO);
    }
    return lstRegionDTO;
  }

  @AuraEnabled(cacheable=true)
  public static String getRegionalManagerByRegionId(String regionId) {
    List<Region__c> regions = [
      SELECT Regional_ManagerId__c
      FROM Region__c
      WHERE Id = :regionId
      WITH SECURITY_ENFORCED
    ];

    if (regions.size() == 0) {
      return null;
    }

    return regions[0].Regional_ManagerId__c;
  }
}