force-app/main/default/objects/Fulfilment_Request__c/Fulfilment_Request__c.object-meta.xml
<CustomObject>
    <label>Fulfilment Request</label>
    <nameField>
        <label>Fulfilment Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfilment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfilment_Request__c/fields/LocationId__c.field-meta.xml
<CustomField>
    <fullName>LocationId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Fulfilment Requests</relationshipLabel>
    <relationshipName>Fulfilment_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfilment_Request__c/fields/Product_ItemId__c.field-meta.xml
<CustomField>
    <fullName>Product_ItemId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage
    >Such Product Item does not exist on the selected Location.</errorMessage>
        <filterItems>
            <field>$Source.LocationId__c</field>
            <operation>equals</operation>
            <valueField>ProductItem.LocationId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ProductItem</referenceTo>
    <relationshipLabel>Fulfilment Requests</relationshipLabel>
    <relationshipName>Fulfilment_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/handlers/FulfilmentRequestHandler/FulfilmentRequestHandler.cls
public with sharing class FulfilmentRequestHandler {
  private static Boolean productItemExistsOnLocation(
    Id productItemId,
    Set<Id> setProductItemId
  ) {
    if (setProductItemId == null) {
      return false;
    }
    return setProductItemId.contains(productItemId);
  }

  private static Set<Id> getProductItemsInLocation(Id locationId) {
    Set<Id> setProductItemIds = new Set<Id>();
    for (ProductItem p : [
      SELECT Id
      FROM ProductItem
      WHERE LocationId = :locationId
      WITH SECURITY_ENFORCED
    ]) {
      setProductItemIds.add(p.Id);
    }

    return setProductItemIds;
  }

  public static void validateProductItemExistsOnLocation(
    List<Fulfilment_Request__c> lstRequests
  ) {
    Map<Id, Set<Id>> mapLocationProductItem = new Map<Id, Set<Id>>();

    for (Fulfilment_Request__c f : lstRequests) {
      mapLocationProductItem.put(f.LocationId__c, null);
    }

    for (Schema.Location l : [
      SELECT Id, (SELECT Id FROM ProductItems)
      FROM Location
      WHERE Id IN :mapLocationProductItem.keySet()
      WITH SECURITY_ENFORCED
    ]) {
      Set<Id> setProductItemId = new Set<Id>();

      for (ProductItem p : l.ProductItems) {
        setProductItemId.add(p.Id);
      }

      mapLocationProductItem.put(l.Id, setProductItemId);
    }

    for (Fulfilment_Request__c f : lstRequests) {
      Set<Id> setProductItemId = mapLocationProductItem.get(f.LocationId__c);
      if (
        FulfilmentRequestHandler.productItemExistsOnLocation(
          f.Product_ItemId__c,
          setProductItemId
        ) == false
      ) {
        f.addError(
          'Such Product Item does not exist on the selected Location.'
        );
      }
    }
  }
}