force-app/main/default/objects/Fulfilment_Request__c/Fulfilment_Request__c.object-meta.xml
<CustomObject>
    <label>Fulfilment Request</label>
    <nameField>
        <label>Fulfilment Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfilment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfilment_Request__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fulfilment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfilment_Request__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <defaultValue>Today() + 1</defaultValue>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fulfilment_Request__c/fields/Fulfilled__c.field-meta.xml
<CustomField>
    <fullName>Fulfilled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fulfilled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fulfilment_Request__c/fields/LocationId__c.field-meta.xml
<CustomField>
    <fullName>LocationId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Fulfilment Requests</relationshipLabel>
    <relationshipName>Fulfilment_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/LocationId__c.field-meta.xml
<CustomField>
    <fullName>LocationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/RegionId__c.field-meta.xml
<CustomField>
    <fullName>RegionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WarehouseController/WarehouseController.cls
public with sharing class WarehouseController {
  public static Warehouse__c updateWarehouseLocationId(
    Id warehouseId,
    Id locationId
  ) {
    Warehouse__c warehouse = [
      SELECT LocationId__c
      FROM Warehouse__c
      WHERE Id = :warehouseId
      WITH SECURITY_ENFORCED
      LIMIT 1
    ];
    warehouse.LocationId__c = locationId;
    return warehouse;
  }

  @AuraEnabled(cacheable=true)
  public static List<Warehouse__c> getWarehousesInRegion(String regionId) {
    return [
      SELECT Id, Name
      FROM Warehouse__c
      WHERE RegionId__c = :regionId
      WITH SECURITY_ENFORCED
      ORDER BY NAME
    ];
  }

  @AuraEnabled(cacheable=true)
  public static List<ProductItem> getProductItemsInWarehouse(
    String warehouseId
  ) {
    Warehouse__c warehouse = [
      SELECT LocationId__c
      FROM Warehouse__c
      WHERE Id = :warehouseId
      WITH SECURITY_ENFORCED
      LIMIT 1
    ];

    if (warehouse == null) {
      return null;
    }

    Id locationId = warehouse.LocationId__c;

    List<ProductItem> lstProductItem = new List<ProductItem>();

    Schema.Location location = [
      SELECT
        Id,
        (
          SELECT
            Product2.Id,
            Product2.Name,
            ProductItemNumber,
            QuantityOnHand,
            SerialNumber
          FROM ProductItems
        )
      FROM Location
      WHERE Id = :locationId
      WITH SECURITY_ENFORCED
    ];

    if (!location.ProductItems.isEmpty()) {
      for (ProductItem p : location.ProductItems) {
        lstProductItem.add(p);
      }
    }

    return lstProductItem;
  }

  @AuraEnabled(cacheable=true)
  public static Warehouse__c getWarehouseInfoById(String warehouseId) {
    return [
      SELECT Id, Name, LocationId__c, LocationId__r.Name
      FROM Warehouse__c
      WHERE Id = :warehouseId
      WITH SECURITY_ENFORCED
      LIMIT 1
    ];
  }

  @AuraEnabled(cacheable=true)
  public static List<Fulfilment_Request__c> getFulfilmentRequestsByWarehouseId(
    String warehouseId
  ) {
    Id locationId = [
      SELECT LocationId__c
      FROM Warehouse__c
      WHERE Id = :warehouseId
    ]
    .LocationId__c;

    List<Fulfilment_Request__c> lstFulfilmentReq = [
      SELECT Id, Name, Assigned_To__c, Fulfilled__c, Due_Date__c
      FROM Fulfilment_Request__c
      WHERE LocationId__c = :locationId
      WITH SECURITY_ENFORCED
      ORDER BY Due_Date__c DESC
    ];

    return lstFulfilmentReq;
  }

  public static void insertLocationsForWarehouses(
    List<Warehouse__c> lstWarehouses
  ) {
    Map<Id, Schema.Location> mapWarehouseToLocation = new Map<Id, Schema.Location>();
    List<Schema.Location> lstLocations = new List<Schema.Location>();
    List<Warehouse__c> lstUpdatedWarehouses = new List<Warehouse__c>();
    for (Warehouse__c w : lstWarehouses) {
      Schema.Location location = new Schema.Location();
      location.Name = w.Name + ' Location';
      location.LocationType = 'Warehouse';
      location.isInventoryLocation = true;
      lstLocations.add(Location);
      mapWarehouseToLocation.put(w.Id, location);
    }

    insert lstLocations;

    for (Id warehouseId : mapWarehouseToLocation.keySet()) {
      Schema.Location location = mapWarehouseToLocation.get(warehouseId);
      Warehouse__c updatedWarehouse = WarehouseController.updateWarehouseLocationId(
        warehouseId,
        location.Id
      );
      lstUpdatedWarehouses.add(updatedWarehouse);
    }

    update lstUpdatedWarehouses;
  }
}