force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/LocationId__c.field-meta.xml
<CustomField>
    <fullName>LocationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/controllers/WarehouseTriggerController/WarehouseTriggerController.cls
public with sharing class WarehouseTriggerController {
  private static Warehouse__c updateWarehouseLocationId(
    Id warehouseId,
    Id locationId
  ) {
    Warehouse__c warehouse = [
      SELECT LocationId__c
      FROM Warehouse__c
      WHERE Id = :warehouseId
      WITH SECURITY_ENFORCED
      LIMIT 1
    ];
    warehouse.LocationId__c = locationId;
    return warehouse;
  }

  public static void insertLocationsForWarehouses(
    List<Warehouse__c> lstWarehouses
  ) {
    Map<Id, Schema.Location> mapWarehouseToLocation = new Map<Id, Schema.Location>();
    List<Schema.Location> lstLocations = new List<Schema.Location>();
    List<Warehouse__c> lstUpdatedWarehouses = new List<Warehouse__c>();
    for (Warehouse__c w : lstWarehouses) {
      Schema.Location location = new Schema.Location();
      location.Name = w.Name + ' Location';
      location.LocationType = 'Warehouse';
      location.isInventoryLocation = true;
      lstLocations.add(Location);
      mapWarehouseToLocation.put(w.Id, location);
    }

    insert lstLocations;

    for (Id warehouseId : mapWarehouseToLocation.keySet()) {
      Schema.Location location = mapWarehouseToLocation.get(warehouseId);
      Warehouse__c updatedWarehouse = WarehouseTriggerController.updateWarehouseLocationId(
        warehouseId,
        location.Id
      );
      lstUpdatedWarehouses.add(updatedWarehouse);
    }

    update lstUpdatedWarehouses;
  }
}